[options]
Architecture = auto
ParallelDownloads = 2

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

# Rubik OS custom repository (uncomment when hosted)
#[rubik]
#Server = https://repo.rubik-os.org/x86_64
#SigLevel = Required
