#
# Rubik OS — pacman.conf
# Minimal configuration with essential repos only
#

[options]
RootDir     = /
DBPath      = /var/lib/pacman/
CacheDir    = /var/cache/pacman/pkg/
LogFile     = /var/log/pacman.log
GPGDir      = /etc/pacman.d/gnupg/
HoldPkg     = pacman glibc
Architecture = auto

# Rubik OS — only keep essential packages
# NoParallelDownloads = 1 (low-RAM systems)
ParallelDownloads = 2

# SigLevel
LocalFileSigLevel = Optional
RemoteFileSigLevel = Required

# Repositories
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

#[multilib]
#Include = /etc/pacman.d/mirrorlist

# Custom Rubik OS repository
#[rubik]
#Server = https://repo.rubik-os.org/$arch
