#
# Rubik OS — pacman.conf
# Minimal configuration with essential repos only
#

[options]
RootDir     = /
DBPath      = /var/lib/pacman/
CacheDir    = /var/cache/pacman/pkg/
LogFile     = /var/log/pacman.log
GPGDir      = /etc/pacman.d/gnupg/
HoldPkg     = pacman glibc
Architecture = auto

# Rubik OS — only keep essential packages
# NoParallelDownloads = 1 (low-RAM systems)
ParallelDownloads = 2

# SigLevel — disabled for build environment (no upstream sig issues)
SigLevel = Never
LocalFileSigLevel = Never
RemoteFileSigLevel = Never

# Repositories
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# [community] was merged into extra in 2025

#[multilib]
#Include = /etc/pacman.d/mirrorlist

# Custom Rubik OS repository
[rubik]
Server = https://erac73.github.io/rubik-os/repo/$arch
